[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py310"
ignore = ["E402"]
respect-gitignore = true

[tool.ruff.lint.isort]
known-first-party = ["src", "test"]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "local-folder",
  "first-party",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
